### ISSUE TITLE
How to restrict access to certain websites

### ISSUE THREAD

**Issue by Alex-Yarkosky** [inTestiGator/pytest-focus#14]
# Description of the Issue
In order to keep the user as focused as possible, it should be investigated how to restrict access to certain sites that could be seen as contributing to less focus.

## Add Detailed Comment with More Information
I plan to look into first if this is possible to do from a script on the terminal and then if it is, I will look into how we can do that and what would be the best way for us to implement this.

## Steps to Reproduce Issue

N/A

## Screenshot (if possible)

N/A

### Assigned Developers

@Alex-Yarkosky

**Comment by Alex-Yarkosky** [comment]
[This](https://www.2daygeek.com/how-to-block-certain-website-access-in-linux-without-hardware-firewall/) is the most promising find so far, it should be noted that it requires the editing of a `/etc/hosts` file & root access. [This](https://serverfault.com/questions/550276/how-to-block-internet-access-to-certain-programs-on-linux), [this](https://askubuntu.com/questions/45072/how-to-control-internet-access-for-each-program), [this](https://unix.stackexchange.com/questions/68956/block-network-access-of-a-process), & [this](https://superuser.com/questions/76558/block-a-user-from-accessing-internet-on-linux) are other potential sources of help that I currently found to be less useful but may be of use as me move along with this.

**Comment by Alex-Yarkosky** [comment]
[Here](https://www.makeuseof.com/tag/focus-4-best-tools-temporarily-block-facebook-co/) are a couple of applications that do things similar to what we are trying to do & might be able to get something from.

**Comment by Alex-Yarkosky** [comment]
[This article](https://www.labnol.org/software/disable-internet-connection/26235/) talks about an application that "toggles the status of your Network Adapter (also known as the LAN adapter or Ethernet card) thus shutting down the Internet for you." Further investigation into whether or not this tool has any use to the development of our plugin should take place.

**Comment by Alex-Yarkosky** [comment]
[This forum post](https://stackoverflow.com/questions/43508741/iptables-script-to-block-all-internet-access-except-for-desired-applications) describes a script opposite to that which we first imagined, i.e. one that instead only allows access to certain specific applications, which we could make be the certain sites we believe they would use to find a solution to their problem. [This article](https://www.cyberciti.biz/faq/linux-limiting-specific-user-shells-internet-bandwidth-usage/), titled "HowTo: Linux Limit A Specific User’s Shell Account Network Bandwidth Using Bash Shell and Trickle," may provide inspiration for how to accomplish this task as well.

**Comment by Alex-Yarkosky** [comment]
@shafferz @yeej2 @baldeosinghm please provide feedback on how this issue should proceed when you get the chance. I will continue to investigate the materials I have provided in the comments above.

**Comment by shafferz** [comment]
@Alex-Yarkosky a few notes:

We shouldn't do the inverse of the intended function (only allow access to specific applications), because we have no way of knowing if the tool being worked on needs access and I don't know if it would be viable to make the program self-allowing. Also, being in Polish doesn't make the option that great for us, either.

The second article, [How to Disable the Internet on your Computer](https://www.labnol.org/software/disable-internet-connection/26235/) seems to be for Windows specifically. We should check for parallels, or keep this in mind when we expand the tool for cross-platform testing. 

The first article seems the most promising, specifically the application [ColdTurkey](http://getcoldturkey.com/). That being said, ColdTurkey seems to be a closed-source software that won't help us develop what is, essentially, the same tool we're creating in a plugin.

**Comment by yeej2** [comment]
I agree with Zach:

I think we should also include some sort of opt-out feature so that they are not trapped forever. Maybe some sort of small penalty for doing it. But yeah, it looks good to me.

**Comment by shafferz** [comment]
This has proved infeasible, and we are moving in another direction.
