### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by yeej2** [inTestiGator/pytest-focus#32]
https://github.com/all-contributors/all-contributors

**Comment by baldeosinghm** [comment]
@all-contributors please add baldeosinghm for code, doc, ideas, review

**Comment by Alex-Yarkosky** [comment]
@allcontributors[bot] please add Alex-Yarkosky for code, content, doc, infra, review

**Comment by Alex-Yarkosky** [comment]
My attempt to add myself failed. Advice is needed.

**Comment by shafferz** [comment]
@all-contributors please add shafferz for code, ideas, review, question

**Comment by shafferz** [comment]
@allcontributors please add Alex-Yarkosky for code, content, doc, infra, review, design

**Comment by ilikerustoo** [comment]
@all-contributors please add baldeosinghm for code, doc, ideas, review, test, platform

**Comment by shafferz** [comment]
@allcontributors please add @Alex-Yarkosky for code, content, doc, infra, review, design

**Comment by ilikerustoo** [comment]
@all-contributors please add ilikerustoo for code, doc, ideas, review, test, platform

**Comment by ilikerustoo** [comment]
@all-contributors please add ilikerustoo for code, doc, ideas, review, test, platform

**Comment by yeej2** [comment]
@all-contributors please add yeej2 for code, doc, ideas, review, test, platform, infra

**Comment by Alex-Yarkosky** [comment]
#45 will add in our current final contributor, however, the status badge for all-contributors is currently at 5 & #45 will make it 6. This is due to #40 and ea13555c2898914c1264b3317ad9d50186abff8a not removing the increase in number of contributors. This is just an FYI so we can change the number when we also go to change the placement of the badge to be in line with the rest of the status badges.

**Comment by shafferz** [comment]
That should be the last of us. Thanks Josh!
